let keys = {};

keys.private = `-----BEGIN RSA PRIVATE KEY-----
MIICWwIBAAKBgHTiuWy2ao/9OQvU+fYTxYbjUjzLxQOb9wzVAPp9WnZzQCaGwteB
w5cUTDgUwkKGgJ+clAbznALIndlClyYgQ77HGt7KK9hkzx3sAziIqOrkkrt7/5FV
Vif1wGFwAIm5ya/hB7SlY0OGAHATHFlV5jfukXgYxsOoD4sXn+KunH2/AgMBAAEC
gYAgG8QaFAYz5bjNAkVkDsxdIIcPwl4tfqOf98dcCCFYlpJRwwU1FCV5lA7X/QPc
KHye2/Fh83uw3BFYhE1nIMfa9wT3/uMJmCBqw0MlmVK4BDJJyIatvYWunGb1AFxR
FCPqIt0OBKeSP471ViQFrKr7Ay4qQYAE/7VNeP0IFaJ9eQJBAOG2niEtxqRQk+jh
+HwrNZqTKtEy0LxvRWBvjR+hJd8BJOHZFEZyKP9dLonGSLRT4SAOv67mVmpc5ZvQ
JAzxKMMCQQCEkdARw4w9SZ1I4SnNYPqu4kIejpuYKA2DBVveBrkYnIOtPqAeeY8G
/1S+/y8uBql6hpFXmalhcTfjGOtCFudVAkEA3ly+ZAlozK/lR2R3HDylTmb1o6rg
IQOt4VeEPEjRumSyJR1q8Au/f/QYyPpi3eRUwPRGutOJBrgGK/5dxbI/aQJAGYQP
LjwbE/jFQy/DYfpWha6a11LPc9vRrfQsGHHm0mvdlEzHeNYgx1IBt7laFVvG5wRb
mSbESTMHdLhpH5FU+QJAJEGD5QOVEhCcJeDYb+mxifxu3fWi27RymF5YF0B5I+4s
euf2yhHPiokc4tLmmej3KkMTz1AMbwPtiMyBbMiXkQ==
-----END RSA PRIVATE KEY-----`;

keys.public = `-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgHTiuWy2ao/9OQvU+fYTxYbjUjzL
xQOb9wzVAPp9WnZzQCaGwteBw5cUTDgUwkKGgJ+clAbznALIndlClyYgQ77HGt7K
K9hkzx3sAziIqOrkkrt7/5FVVif1wGFwAIm5ya/hB7SlY0OGAHATHFlV5jfukXgY
xsOoD4sXn+KunH2/AgMBAAE=
-----END PUBLIC KEY-----`;

module.exports = keys;